export const CARD_VERSION = '1.0.5'
export const SLIDER_VERSION = '2.0.3'
export const BUTTON_LIGHT_VERSION = '0.0.1'
export const BUTTON_COVER_VERSION = '0.0.1'
export const FOOTER_VERSION = '0.0.3'
export const DASHBOARD_VERSION = '0.0.1'
