name: HACS validation
on:
    push:
        branches:
            - main
            - beta
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: HACS validation
              uses: "hacs/action@main"
              with:
                  category: "plugin"
